// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/**
 * @title TokenLaunchFee
 * @notice Collects the one-time launch fee (in Base ETH) for new token listings.
 *
 * The backend sets minFeeWei dynamically based on the current ETH/USD price
 * so that the fee always equals approximately $20 USD.
 *
 * On payment the LaunchFeeReceived event is emitted; the backend detects this
 * event and begins the wrapped-token deployment pipeline.
 *
 * ETH is forwarded to the treasury / liquidity fund on each payment.
 * The owner can update the minimum fee and the treasury address at any time.
 */
contract TokenLaunchFee is Ownable, ReentrancyGuard {
    address public treasury;
    uint256 public minFeeWei;

    event LaunchFeeReceived(
        address indexed payer,
        bytes32 indexed launchId,
        uint256 amount
    );
    event TreasuryUpdated(address indexed oldTreasury, address indexed newTreasury);
    event MinFeeUpdated(uint256 oldFee, uint256 newFee);

    constructor(address _treasury, uint256 _minFeeWei) Ownable(msg.sender) {
        require(_treasury != address(0), "LaunchFee: zero treasury");
        treasury = _treasury;
        minFeeWei = _minFeeWei;
    }

    /**
     * @notice Pay the launch fee.  ETH is forwarded immediately to treasury.
     * @param launchId  Off-chain UUID (bytes32) generated by the backend for this launch.
     */
    function payLaunchFee(bytes32 launchId) external payable nonReentrant {
        require(msg.value >= minFeeWei, "LaunchFee: fee too low");
        require(launchId != bytes32(0), "LaunchFee: zero launchId");

        // Forward ETH to treasury immediately
        (bool ok, ) = treasury.call{value: msg.value}("");
        require(ok, "LaunchFee: treasury transfer failed");

        emit LaunchFeeReceived(msg.sender, launchId, msg.value);
    }

    // ── Admin ─────────────────────────────────────────────────────────────────

    function setTreasury(address newTreasury) external onlyOwner {
        require(newTreasury != address(0), "LaunchFee: zero address");
        emit TreasuryUpdated(treasury, newTreasury);
        treasury = newTreasury;
    }

    function setMinFee(uint256 newFee) external onlyOwner {
        emit MinFeeUpdated(minFeeWei, newFee);
        minFeeWei = newFee;
    }

    /// @notice Emergency ETH recovery if ETH somehow accumulates (should not happen normally).
    function sweep() external onlyOwner {
        (bool ok, ) = owner().call{value: address(this).balance}("");
        require(ok, "LaunchFee: sweep failed");
    }

    receive() external payable {}
}
