'use strict';
const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('path');
const fs   = require('fs');
const { Worker } = require('worker_threads');

let win = null;
let miningWorker = null;

// Pre-built worker bundle (CJS, includes ethereum-cryptography inline)
// Generated by: node scripts/bundle.mjs  (uses workspace's esbuild)
const WORKER_BUNDLE_PATH = path.join(__dirname, 'worker-bundle.js');

// ── Window ─────────────────────────────────────────────────────────────────

function createWindow() {
  win = new BrowserWindow({
    width: 860,
    height: 620,
    minWidth: 760,
    minHeight: 560,
    frame: false,
    backgroundColor: '#111111',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });
  win.loadFile(path.join(__dirname, 'renderer', 'index.html'));
  win.on('closed', () => { win = null; });
}

app.whenReady().then(createWindow);
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
app.on('activate', () => { if (!win) createWindow(); });

// ── Window controls ─────────────────────────────────────────────────────────

ipcMain.on('win:minimize', () => win?.minimize());
ipcMain.on('win:close',    () => { stopMining(); app.quit(); });

// ── Mining ─────────────────────────────────────────────────────────────────

/**
 * The mining loop runs in a worker_threads Worker so the Electron main
 * process (and therefore the UI) stays fully responsive under heavy CPU load.
 *
 * worker-bundle.js is a pre-built CJS bundle (esbuild, ethereum-cryptography
 * inlined) generated by:  node scripts/bundle.mjs
 * This means the Electron app has zero JS runtime npm dependencies.
 */

function startMining(settings) {
  if (miningWorker) return;

  if (!fs.existsSync(WORKER_BUNDLE_PATH)) {
    win?.webContents.send('mining:event', {
      type: 'error',
      msg: 'worker-bundle.js not found. Run: node scripts/bundle.mjs',
    });
    return;
  }

  miningWorker = new Worker(WORKER_BUNDLE_PATH, {
    workerData: {
      nodeUrl:   settings.nodeUrl.replace(/\/$/, ''),
      address:   settings.address,
      intensity: settings.intensity,
    },
  });

  miningWorker.on('message', (msg) => {
    win?.webContents.send('mining:event', msg);
  });

  miningWorker.on('error', (err) => {
    win?.webContents.send('mining:event', { type: 'error', msg: err.message });
    miningWorker = null;
  });

  miningWorker.on('exit', () => {
    miningWorker = null;
    win?.webContents.send('mining:event', { type: 'stopped' });
  });
}

function stopMining() {
  if (miningWorker) {
    miningWorker.postMessage('stop');
  }
}

ipcMain.on('mining:start', (_e, settings) => startMining(settings));
ipcMain.on('mining:stop',  ()           => stopMining());
