/**
 * Token Launch DB
 *
 * Tracks the full lifecycle of a token launch request:
 *   pending_payment → payment_confirmed → pending_gas → deploying → live | failed
 *
 * For EVM chains the "pending_gas" step waits for the project to fund the
 * bridge deployment wallet.  Non-EVM chains skip that step and go straight
 * to deploying (escrow-wallet model, no on-chain contract needed on the
 * native side).
 */

import pg from "pg";

const pool = new pg.Pool({
  connectionString: process.env.DATABASE_URL,
  max: 5,
  idleTimeoutMillis: 10_000,
  connectionTimeoutMillis: 5_000,
});

pool.on("error", (err) => {
  console.error("[launch-db] pool error:", err.message);
});

// ── Table bootstrap ──────────────────────────────────────────────────────────

export async function ensureLaunchTable(): Promise<void> {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS token_launches (
      id                   TEXT PRIMARY KEY,
      status               TEXT NOT NULL DEFAULT 'pending_payment',

      -- Token identity
      symbol               TEXT NOT NULL,
      wrapped_symbol       TEXT NOT NULL,
      token_name           TEXT NOT NULL,
      decimals             INT  NOT NULL DEFAULT 18,

      -- Chain metadata
      chain_type           TEXT NOT NULL,  -- 'evm' | 'utxo' | 'privacy' | 'custom'
      chain_name           TEXT NOT NULL,
      chain_id             TEXT,           -- EVM chain ID (numeric string)
      rpc_url              TEXT NOT NULL,
      explorer_url         TEXT,

      -- Chain technical details (for adapter selection)
      consensus            TEXT,           -- 'pow' | 'pos' | 'other'
      cryptography         TEXT,           -- 'secp256k1' | 'ed25519' | 'other'
      address_format       TEXT,           -- 'hex' | 'base58' | 'bech32' | 'custom'
      utxo_network         TEXT,           -- for base58/bech32: 'bitcoin'|'litecoin'|'dogecoin'|'dash'|'zcash'|'other'
      tx_model             TEXT,           -- 'account' | 'utxo' | 'privacy'
      confirmations_req    INT  NOT NULL DEFAULT 6,

      -- Payment
      fee_tx_hash          TEXT,
      fee_payer            TEXT,
      fee_amount_eth       TEXT,

      -- Bridge wallet (generated by server)
      bridge_wallet_address TEXT,
      bridge_wallet_type    TEXT,          -- 'evm_reused' | 'utxo_derived' | 'generated'
      bridge_private_key_encrypted TEXT,   -- AES-256-GCM encrypted private key (non-EVM generated wallets only)

      -- Deployed addresses (filled in during deployment)
      wrapped_token_address TEXT,
      universal_bridge_address TEXT,
      native_bridge_address TEXT,

      -- Submitter
      submitter_address    TEXT NOT NULL,

      -- Misc
      error_msg            TEXT,
      created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  // Indexes for common lookups
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_token_launches_status   ON token_launches (status);
    CREATE INDEX IF NOT EXISTS idx_token_launches_submitter ON token_launches (submitter_address);
    CREATE INDEX IF NOT EXISTS idx_token_launches_symbol    ON token_launches (wrapped_symbol);
  `);

  // Migrations
  await pool.query(`
    ALTER TABLE token_launches
      ADD COLUMN IF NOT EXISTS bridge_private_key_encrypted TEXT
  `);
  await pool.query(`
    ALTER TABLE token_launches
      ADD COLUMN IF NOT EXISTS utxo_network TEXT
  `);
  await pool.query(`
    ALTER TABLE token_launches
      ADD COLUMN IF NOT EXISTS wallet_download_url TEXT
  `);
  await pool.query(`
    ALTER TABLE token_launches
      ADD COLUMN IF NOT EXISTS escrow_mode TEXT DEFAULT 'auto'
  `);
  await pool.query(`
    ALTER TABLE token_launches
      ADD COLUMN IF NOT EXISTS admin_notes TEXT
  `);
  await pool.query(`
    ALTER TABLE token_launches
      ADD COLUMN IF NOT EXISTS operator_message TEXT
  `);
}

// ── Types ────────────────────────────────────────────────────────────────────

export type LaunchStatus =
  | "pending_payment"
  | "payment_confirmed"
  | "pending_gas"
  | "deploying"
  | "awaiting_escrow"
  | "live"
  | "failed";

export interface TokenLaunch {
  id: string;
  status: LaunchStatus;
  symbol: string;
  wrapped_symbol: string;
  token_name: string;
  decimals: number;
  chain_type: string;
  chain_name: string;
  chain_id?: string;
  rpc_url: string;
  explorer_url?: string;
  consensus?: string;
  cryptography?: string;
  address_format?: string;
  utxo_network?: string;
  tx_model?: string;
  confirmations_req: number;
  fee_tx_hash?: string;
  fee_payer?: string;
  fee_amount_eth?: string;
  bridge_wallet_address?: string;
  bridge_wallet_type?: string;
  bridge_private_key_encrypted?: string;
  wrapped_token_address?: string;
  universal_bridge_address?: string;
  native_bridge_address?: string;
  submitter_address: string;
  wallet_download_url?: string;
  escrow_mode?: "auto" | "manual";
  admin_notes?: string;
  operator_message?: string;
  error_msg?: string;
  created_at: Date;
  updated_at: Date;
}

// ── CRUD ─────────────────────────────────────────────────────────────────────

export async function createLaunch(data: Omit<TokenLaunch, "status" | "created_at" | "updated_at">): Promise<TokenLaunch> {
  const res = await pool.query<TokenLaunch>(
    `INSERT INTO token_launches (
       id, symbol, wrapped_symbol, token_name, decimals,
       chain_type, chain_name, chain_id, rpc_url, explorer_url,
       consensus, cryptography, address_format, utxo_network, tx_model, confirmations_req,
       submitter_address
     ) VALUES (
       $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17
     ) RETURNING *`,
    [
      data.id, data.symbol, data.wrapped_symbol, data.token_name, data.decimals,
      data.chain_type, data.chain_name, data.chain_id ?? null, data.rpc_url, data.explorer_url ?? null,
      data.consensus ?? null, data.cryptography ?? null, data.address_format ?? null,
      data.utxo_network ?? null, data.tx_model ?? null, data.confirmations_req,
      data.submitter_address,
    ],
  );
  return res.rows[0];
}

export async function getLaunch(id: string): Promise<TokenLaunch | null> {
  const res = await pool.query<TokenLaunch>(
    "SELECT * FROM token_launches WHERE id = $1",
    [id],
  );
  return res.rows[0] ?? null;
}

export async function getLiveLaunches(): Promise<TokenLaunch[]> {
  const res = await pool.query<TokenLaunch>(
    "SELECT * FROM token_launches WHERE status = 'live' ORDER BY created_at DESC",
  );
  return res.rows;
}

export async function getLaunchesByStatus(status: LaunchStatus): Promise<TokenLaunch[]> {
  const res = await pool.query<TokenLaunch>(
    "SELECT * FROM token_launches WHERE status = $1 ORDER BY created_at ASC",
    [status],
  );
  return res.rows;
}

export async function getLaunchesBySubmitter(address: string): Promise<TokenLaunch[]> {
  const res = await pool.query<TokenLaunch>(
    "SELECT * FROM token_launches WHERE submitter_address = $1 ORDER BY created_at DESC",
    [address.toLowerCase()],
  );
  return res.rows;
}

export async function getAllLaunches(limit = 100): Promise<TokenLaunch[]> {
  const res = await pool.query<TokenLaunch>(
    "SELECT * FROM token_launches ORDER BY updated_at DESC LIMIT $1",
    [limit],
  );
  return res.rows;
}

export async function getLaunchesAwaitingEscrow(): Promise<TokenLaunch[]> {
  const res = await pool.query<TokenLaunch>(
    "SELECT * FROM token_launches WHERE status = 'awaiting_escrow' ORDER BY created_at ASC",
  );
  return res.rows;
}

export async function updateLaunchFields(
  id: string,
  patch: Partial<Pick<TokenLaunch,
    | "status"
    | "fee_tx_hash" | "fee_payer" | "fee_amount_eth"
    | "bridge_wallet_address" | "bridge_wallet_type" | "bridge_private_key_encrypted"
    | "wrapped_token_address" | "universal_bridge_address" | "native_bridge_address"
    | "wallet_download_url" | "escrow_mode" | "admin_notes" | "operator_message"
    | "error_msg"
  >>,
): Promise<void> {
  const sets: string[] = ["updated_at = NOW()"];
  const vals: unknown[] = [id];
  let idx = 2;

  for (const [key, val] of Object.entries(patch)) {
    if (val !== undefined) {
      sets.push(`${key} = $${idx++}`);
      vals.push(val);
    }
  }

  if (sets.length === 1) return;

  await pool.query(
    `UPDATE token_launches SET ${sets.join(", ")} WHERE id = $1`,
    vals,
  );
}

export async function updateLaunchStatus(
  id: string,
  status: LaunchStatus,
  extra: Partial<Pick<TokenLaunch,
    "fee_tx_hash" | "fee_payer" | "fee_amount_eth" |
    "bridge_wallet_address" | "bridge_wallet_type" | "bridge_private_key_encrypted" |
    "wrapped_token_address" | "universal_bridge_address" | "native_bridge_address" |
    "wallet_download_url" | "escrow_mode" | "admin_notes" | "operator_message" |
    "error_msg"
  >> = {},
): Promise<void> {
  await updateLaunchFields(id, { status, ...extra });
}
