// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ember-delta-mobile/DrawerLayout.tsx": () => import("../components/mockups/ember-delta-mobile/DrawerLayout.tsx"),
  "./components/mockups/ember-delta-mobile/ScrollStack.tsx": () => import("../components/mockups/ember-delta-mobile/ScrollStack.tsx"),
  "./components/mockups/ember-delta-mobile/TabNav.tsx": () => import("../components/mockups/ember-delta-mobile/TabNav.tsx")
};
